### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayerFactory;

### ISSUE THREAD

**Issue by pushpender100** [animeng/flutter_export_video_frame#11]
Here is code.

var streamImage = await ExportVideoFrame.exportImagesFromFile(
                 tempVideo, Duration(seconds: 1), 0);

**Comment by ArturAntin** [comment]
Same problem.
It only happens on android devices and it has something to do with the media info plugin used in the package.

this is the full error message:
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayerFactory;
at asia.ivity.mediainfo.MediaInfoPlugin.ensureExoPlayer(MediaInfoPlugin.java:365)
at asia.ivity.mediainfo.MediaInfoPlugin.handleMediaInfoExoPlayer(MediaInfoPlugin.java:176)
at asia.ivity.mediainfo.MediaInfoPlugin.lambda$handleMediaInfo$0$MediaInfoPlugin(MediaInfoPlugin.java:132)
at asia.ivity.mediainfo.-$$Lambda$MediaInfoPlugin$FmgGTlALyNlnLFUldbmZd5v5ELM.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:7582)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.ExoPlayerFactory" on path: DexPathList[[zip file "/data/app/com.example.ml_test-NHOgUpUdvcFcZjPMVstjeg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.ml_test-NHOgUpUdvcFcZjPMVstjeg==/lib/arm64, /data/app/com.example.ml_test-NHOgUpUdvcFcZjPMVstjeg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`

**Comment by navin-zignuts** [comment]
Hello I am facing the same issue and not able to find the solution, as it's only stop working in android app, as iOS is working fine with the same implementation 

Any work round for this ?

**Comment by isaactinghong** [comment]
facing the same issue too!

**Comment by isaactinghong** [comment]
my workaround is copy the whole logic and use something other than media_info to determine the video length
