### ISSUE TITLE
No longer generating thumbnails in Android and throwing exception

### ISSUE THREAD

**Issue by Chetan-3110** [animeng/flutter_export_video_frame#8]
I have already checked for the permission and existence of file. 

> Logs
E/MethodChannel#export_video_frame( 5319): Failed to handle method call
E/MethodChannel#export_video_frame( 5319): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
E/MethodChannel#export_video_frame( 5319):      at androidx.core.content.ContextCompat.checkSelfPermission(ContextCompat.java:555)
E/MethodChannel#export_video_frame( 5319):      at com.mengtnt.export_video_frame.PermissionManager.isPermissionGranted(PermissionManager.java:53)
E/MethodChannel#export_video_frame( 5319):      at com.mengtnt.export_video_frame.ExportVideoFramePlugin.onMethodCall(ExportVideoFramePlugin.java:65)
E/MethodChannel#export_video_frame( 5319):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#export_video_frame( 5319):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#export_video_frame( 5319):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#export_video_frame( 5319):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#export_video_frame( 5319):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#export_video_frame( 5319):      at android.os.Looper.loopOnce(Looper.java:161)
E/MethodChannel#export_video_frame( 5319):      at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#export_video_frame( 5319):      at android.app.ActivityThread.main(ActivityThread.java:7839)
E/MethodChannel#export_video_frame( 5319):      at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#export_video_frame( 5319):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#export_video_frame( 5319):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

After Searching, I found this:
https://stackoverflow.com/questions/37322645/nullpointerexception-when-trying-to-check-permissions/37323440

It might help you to fix the issue.

**Comment by Chetan-3110** [comment]
I don't know why but running a clean build fixed the issue. So, closing this issue.
